// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcmoo-zva0DrX_D5xnXe4sjoZ71arO3HU',
    appId: '1:553315913700:web:92a97201099441e68d01f1',
    messagingSenderId: '553315913700',
    projectId: 'roamora-9ab71',
    authDomain: 'roamora-9ab71.firebaseapp.com',
    storageBucket: 'roamora-9ab71.firebasestorage.app',
    measurementId: 'G-GL7R9YNQ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWKEokRLOdfMtVDHSOQUGBHv_sxWfz6o',
    appId: '1:553315913700:android:5eb4a71c9ff133548d01f1',
    messagingSenderId: '553315913700',
    projectId: 'roamora-9ab71',
    storageBucket: 'roamora-9ab71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_mFa-m8OJuaGRo-2dQowK3oVFYpxh8w',
    appId: '1:553315913700:ios:792961981eb8fea78d01f1',
    messagingSenderId: '553315913700',
    projectId: 'roamora-9ab71',
    storageBucket: 'roamora-9ab71.firebasestorage.app',
    iosBundleId: 'com.example.roamora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_mFa-m8OJuaGRo-2dQowK3oVFYpxh8w',
    appId: '1:553315913700:ios:792961981eb8fea78d01f1',
    messagingSenderId: '553315913700',
    projectId: 'roamora-9ab71',
    storageBucket: 'roamora-9ab71.firebasestorage.app',
    iosBundleId: 'com.example.roamora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcmoo-zva0DrX_D5xnXe4sjoZ71arO3HU',
    appId: '1:553315913700:web:9249e6d3c75c729a8d01f1',
    messagingSenderId: '553315913700',
    projectId: 'roamora-9ab71',
    authDomain: 'roamora-9ab71.firebaseapp.com',
    storageBucket: 'roamora-9ab71.firebasestorage.app',
    measurementId: 'G-8TQH2R1SB5',
  );
}
